server:
  port: 23464
  registry-port: 8888

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-server

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.registry-port}/eureka

spring:
  kafka:
    consumer:
      group-id: delegate
      auto-offset-reset: latest
    bootstrap-servers: kafka-server:9092
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: 0904cb45e8277258ca18
            client-secret: 05424b6c6e00b3bebeb30e42073933b5a0803c9a
            authorization-grant-type: client_credentials
            scope: read:user
      resourceserver:
        jwt:
          issuer-uri: http://public-auth:9000
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO

route:
  intermediate:
    kanbanHistoryLink: http://kanban-project/kanban/history/{0}?page={1}&size={2}
    managementHistoryLink: http://management-service/management/history?page={0}&size={1}
